services:
  events:
    build: 
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres-db
      - redis
    env_file:
      - ./.env.docker

  postgres-db:
    image: postgres:16.3
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

  redis:
    image: redis:7.4
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning 
    volumes: 
      - redis_data:/data
    environment:
      - REDIS_URL=redis://redis:6379

  redisinsight:
    image: redislabs/redisinsight:1.11.0
    container_name: redisinsight
    restart: always
    ports:
      - "8001:8001"
    depends_on:
      - redis
    volumes:
      - redisinsight_data:/db 

  worker:
    build:
      context: .
    hostname: worker
    entrypoint: celery
    command: -A config.celery.app worker --loglevel=info
    volumes:
      - .:/config
    links:
      - redis
    depends_on:
      - redis
    env_file:
      - .env


      

volumes:
  postgres_data:
  redis_data:
  redisinsight_data:
